use PlanIt;
#insert into PlanItUsers (Email , Password, role , Department, Year_Started , FName , Lname) values ("testStud@school.edu","Letmein!1","student","tempDepartment","2021","MrStudent","McStudent");
select * from PlanItUsers;
#insert into Credentials (CredentialName , Type) values ("Software_Engineering","Major");
#insert into Credentials (CredentialName , Type) values ("Game_Develepement","Major");
#insert into Credentials (CredentialName , Type) values ("Mathematics" , "Major");
#insert into Credentials (CredentialName , Type) values ("Criminology" , "Major");
#insert into Credentials (CredentialName , Type) values ("English" , "Major");
#insert into Credentials (CredentialName , Type) values ("Interactive_Design" , "Cert"); 
#insert into Credentials (CredentialName , Type) values ("International_Immerson" , "Cert");
#insert into Credentials (CredentialName , Type) values ("Ancients_Alive:Classics_In_Context" , "Cert");
#insert into Credentials (CredentialName , Type) values ("Computer_Science", "Minor");
select * from Credentials;
#Alter table Courses modify column Semester ENUM("Fall","Spring","Winter","Summer","Both");
#insert into Courses (CoursePrefix,CourseName,CourseCode,Semester,CreditHours) values ("CSCI","Discrete_Mathematics",241,"fall",3);
#insert into Courses (CoursePrefix,CourseName,CourseCode,Semester,CreditHours) values ("CSCI","Intro_To_Computer_Science",251,"fall",4);
#insert into Courses (CoursePrefix,CourseName,CourseCode,Semester,CreditHours) values ("MATH","Calculus_I",231,"fall",4);
#insert into Courses (CoursePrefix,CourseName,CourseCode,Semester,CreditHours) values ("CSCI","Data_Structures",261,"fall",4);
#insert into Courses (CoursePrefix,CourseName,CourseCode,Semester,CreditHours) values ("CRIM","Intro_To_Criminology",102,"fall",3);
#insert into Courses (CoursePrefix,CourseName,CourseCode,Semester,CreditHours) values ("ENGL","British Literature I",201,"fall",3);
#insert into Courses (CoursePrefix,CourseName,CourseCode,Semester,CreditHours) values ("ARTZ","Interactive_Design_And_Aesthetics",314,"fall",3);
#insert into Courses (CoursePrefix,CourseName,CourseCode,Semester,CreditHours) values ("ENGL","Comparative_Mythology",212,"fall",3);
#insert into Courses (CoursePrefix,CourseName,CourseCode,Semester,CreditHours) values ("HIST","Ancient_Civilizations",110,"fall",3);
select * from Courses;
#insert into Credentials_has_Courses (Credentials_CredentialID, Courses_UniqueCourseID) values (1,1);
#insert into Credentials_has_Courses (Credentials_CredentialID, Courses_UniqueCourseID) values (1,2);
#insert into Credentials_has_Courses (Credentials_CredentialID, Courses_UniqueCourseID) values (1,3);
#insert into Credentials_has_Courses (Credentials_CredentialID, Courses_UniqueCourseID) values (1,4);
#insert into Credentials_has_Courses (Credentials_CredentialID, Courses_UniqueCourseID) values (3,1);
#insert into Credentials_has_Courses (Credentials_CredentialID, Courses_UniqueCourseID) values (3,2);
#insert into Credentials_has_Courses (Credentials_CredentialID, Courses_UniqueCourseID) values (3,3);
#insert into Credentials_has_Courses (Credentials_CredentialID, Courses_UniqueCourseID) values (3,4);
#insert into Credentials_has_Courses (Credentials_CredentialID, Courses_UniqueCourseID) values (4,3);
#insert into Credentials_has_Courses (Credentials_CredentialID, Courses_UniqueCourseID) values (5,5);
#insert into Credentials_has_Courses (Credentials_CredentialID, Courses_UniqueCourseID) values (6,6);
#insert into Credentials_has_Courses (Credentials_CredentialID, Courses_UniqueCourseID) values (6,8);
#insert into Credentials_has_Courses (Credentials_CredentialID, Courses_UniqueCourseID) values (7,7);
#insert into Credentials_has_Courses (Credentials_CredentialID, Courses_UniqueCourseID) values (8,8);
#insert into Credentials_has_Courses (Credentials_CredentialID, Courses_UniqueCourseID) values (9,9);
#insert into Credentials_has_Courses (Credentials_CredentialID, Courses_UniqueCourseID) values (10,4);
select * from Credentials_has_Courses;
