-- MySQL Script generated by MySQL Workbench
-- Wed Oct  6 09:51:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema PlanItTest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PlanItTest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PlanItTest` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `PlanItTest` ;

-- -----------------------------------------------------
-- Table `PlanItTest`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlanItTest`.`Courses` ;

CREATE TABLE IF NOT EXISTS `PlanItTest`.`Courses` (
  `UniqueCourseID` INT NOT NULL AUTO_INCREMENT,
  `CoursePrefix` VARCHAR(6) NOT NULL,
  `CourseName` VARCHAR(45) NOT NULL,
  `CourseCode` INT NOT NULL,
  `Semester` ENUM("Fall", "Spring", "Both", "Summer") NOT NULL,
  `CreditHours` INT NOT NULL,
  PRIMARY KEY (`UniqueCourseID`, `CoursePrefix`, `CourseCode`),
  UNIQUE INDEX `UniqueCourseID_UNIQUE` (`UniqueCourseID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;
CREATE INDEX fk_StudentCourseTable_Courses1_idx on Courses (CoursePrefix);
CREATE INDEX fk_StudentCourseTable_Courses2_idx on Courses (CourseCode);


-- -----------------------------------------------------
-- Table `PlanItTest`.`UserAccountsTest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlanItTest`.`UserAccountsTest` ;

CREATE TABLE IF NOT EXISTS `PlanItTest`.`UserAccountsTest` (
  `UserId` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(60) NOT NULL,
  `Password` VARCHAR(60) NOT NULL,
  `Role` ENUM('student', 'admin', 'advisor') NOT NULL,
  `Department` VARCHAR(60) NOT NULL,
  `Year_Started` YEAR NOT NULL,
  `Fname` VARCHAR(45) NOT NULL,
  `Lname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserId`, `Email`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `PlanItTest`.`StudentCourseTable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PlanItTest`.`StudentCourseTable` ;

CREATE TABLE IF NOT EXISTS `PlanItTest`.`StudentCourseTable` (
  `UserId` INT UNSIGNED NOT NULL,
  `CoursePrefix` VARCHAR(6) NOT NULL,
  `CourseCode` INT NOT NULL,
  `PlanYear` ENUM("fr", "soph", "jr", "Sr") NULL,
  `PlanSemester` ENUM("Fall", "Spring", "Summer") NULL,
  PRIMARY KEY (`UserId`, `CoursePrefix`, `CourseCode`),
  INDEX `fk_StudentCourseTable_Courses1_idx` (`CoursePrefix` ASC) VISIBLE,
  INDEX `fk_StudentCourseTable_Courses2_idx` (`CourseCode` ASC) VISIBLE,
  CONSTRAINT `fk_StudentCourseTable_Courses1`
    FOREIGN KEY (`CoursePrefix`)
    REFERENCES `PlanItTest`.`Courses` (`CoursePrefix`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StudentCourseTable_UserAccountsTest1`
    FOREIGN KEY (`UserId`)
    REFERENCES `PlanItTest`.`UserAccountsTest` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StudentCourseTable_Courses2`
    FOREIGN KEY (`CourseCode`)
    REFERENCES `PlanItTest`.`Courses` (`CourseCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
